// src/components/ReconciliationResult.jsx
import React from "react";
import ConfidenceBadge from "./ConfidenceBadge";

function ScoreBar({ label, value }) {
  const pct = Math.round((value || 0) * 100);
  return (
    <div style={{ marginBottom: "10px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "4px" }}>
        <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: "11px", color: "var(--muted)" }}>{label}</span>
        <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: "11px", color: "var(--text-soft)" }}>{pct}%</span>
      </div>
      <div style={{ height: "5px", background: "var(--border)", borderRadius: "3px", overflow: "hidden" }}>
        <div style={{ width: `${pct}%`, height: "100%", background: "linear-gradient(90deg, #a78bfa, #00e5a0)", borderRadius: "3px", transition: "width 1s ease" }} />
      </div>
    </div>
  );
}

export default function ReconciliationResult({ result }) {
  if (!result) return null;

  const { status, confidence, invoice, best_match, score_breakdown, explanation, warnings, fx_trace, fee_trace } = result;
  const expectedCredit = fee_trace?.expected_credit ?? fee_trace?.net_after_fee;
  const totalFee = fee_trace?.total_fee ?? fee_trace?.fee_amount;

  return (
    <div style={styles.card}>
      {/* Top bar */}
      <div style={styles.topBar}>
        <div>
          <div style={{ fontFamily: "'Syne', sans-serif", fontSize: "18px", fontWeight: 700, color: "var(--text)", marginBottom: "8px" }}>
            Reconciliation Result
          </div>
          <ConfidenceBadge status={status} confidence={confidence} />
        </div>
        <div style={styles.invoiceTag}>
          <div style={styles.invoiceTagLabel}>Invoice</div>
          <div style={styles.invoiceTagValue}>{invoice?.invoice_number || "—"}</div>
        </div>
      </div>

      {/* Summary grid */}
      <div style={styles.summaryGrid}>
        <div style={styles.summaryItem}>
          <div style={styles.summaryLabel}>Invoice Amount</div>
          <div style={styles.summaryValue}>{invoice?.currency} {invoice?.amount?.toFixed(2)}</div>
        </div>
        <div style={styles.arrow}>→</div>
        <div style={styles.summaryItem}>
          <div style={styles.summaryLabel}>FX Converted</div>
          <div style={styles.summaryValue}>{fx_trace?.target_currency} {fx_trace?.converted_amount?.toFixed(2)}</div>
          <div style={styles.summaryNote}>@ {fx_trace?.rate} on {fx_trace?.rate_date}</div>
        </div>
        <div style={styles.arrow}>→</div>
        <div style={styles.summaryItem}>
          <div style={styles.summaryLabel}>Expected After Fee</div>
          <div style={styles.summaryValue}>{fee_trace?.currency} {expectedCredit?.toFixed(2)}</div>
          <div style={styles.summaryNote}>Fee: {fee_trace?.currency} {totalFee?.toFixed(2)}</div>
        </div>
        <div style={styles.arrow}>vs</div>
        <div style={styles.summaryItem}>
          <div style={styles.summaryLabel}>Bank Credited</div>
          <div style={{ ...styles.summaryValue, color: status === "matched" ? "#00e5a0" : "#f5a623" }}>
            {best_match?.currency} {best_match?.credit_amount?.toFixed(2)}
          </div>
          <div style={styles.summaryNote}>{best_match?.date}</div>
        </div>
      </div>

      {/* Explanation box */}
      <div style={styles.explanationBox}>
        <div style={styles.explanationHeader}>
          <span style={styles.pill}>RECONCILIATION SUMMARY</span>
          <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: "10px", color: "var(--muted-faint)" }}>Generated by Chutes</span>
        </div>
        <p style={styles.explanationText}>{explanation}</p>
      </div>

      {/* Score breakdown */}
      {score_breakdown && (
        <div style={styles.scoreSection}>
          <div style={styles.pill}>SCORE BREAKDOWN</div>
          <div style={{ marginTop: "12px" }}>
            <ScoreBar label="Date Match" value={score_breakdown.date_score} />
            <ScoreBar label="Reference Match" value={score_breakdown.reference_score} />
            <ScoreBar label="Amount Match" value={score_breakdown.amount_score} />
          </div>
        </div>
      )}

      {/* Best match row */}
      {best_match && (
        <div style={styles.bestMatchRow}>
          <span style={styles.pill}>MATCHED BANK ROW</span>
          <div style={{ marginTop: "10px", display: "flex", gap: "20px", flexWrap: "wrap" }}>
            <div style={styles.matchField}><span style={styles.matchLabel}>Row</span><span style={styles.matchVal}>{best_match.row_id}</span></div>
            <div style={styles.matchField}><span style={styles.matchLabel}>Date</span><span style={styles.matchVal}>{best_match.date}</span></div>
            <div style={styles.matchField}><span style={styles.matchLabel}>Description</span><span style={styles.matchVal}>{best_match.description}</span></div>
            <div style={styles.matchField}><span style={styles.matchLabel}>Credit</span><span style={{ ...styles.matchVal, color: "#00e5a0" }}>{best_match.currency} {best_match.credit_amount?.toFixed(2)}</span></div>
          </div>
        </div>
      )}

      {/* Warnings */}
      {warnings?.length > 0 && (
        <div style={styles.warningBox}>
          {warnings.map((w, i) => (
            <div key={i} style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: "11px", color: "#f5a623", marginBottom: "3px" }}>⚠ {w}</div>
          ))}
        </div>
      )}
    </div>
  );
}

const styles = {
  card: {
    background: "var(--panel)",
    border: "1px solid var(--border)",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "var(--shadow)",
    minWidth: 0,
    overflow: "hidden",
  },
  topBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "24px",
    flexWrap: "wrap",
    gap: "16px",
  },
  invoiceTag: {
    background: "var(--panel-strong)",
    border: "1px solid var(--border-strong)",
    borderRadius: "8px",
    padding: "10px 16px",
    textAlign: "right",
    maxWidth: "100%",
    minWidth: 0,
  },
  invoiceTagLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "10px",
    color: "var(--muted-soft)",
    marginBottom: "2px",
  },
  invoiceTagValue: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "14px",
    fontWeight: 700,
    color: "var(--text)",
    letterSpacing: "0.04em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(120px,1fr) auto minmax(140px,1fr) auto minmax(150px,1fr) auto minmax(140px,1fr)",
    alignItems: "start",
    gap: "10px",
    padding: "16px",
    background: "var(--panel-soft)",
    borderRadius: "10px",
    marginBottom: "20px",
    overflowX: "auto",
  },
  summaryItem: {
    minWidth: 0,
  },
  summaryLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "10px",
    color: "var(--muted-soft)",
    marginBottom: "4px",
    letterSpacing: "0.04em",
  },
  summaryValue: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "15px",
    fontWeight: 700,
    color: "var(--text)",
    overflowWrap: "anywhere",
  },
  summaryNote: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "10px",
    color: "var(--muted-faint)",
    marginTop: "2px",
  },
  arrow: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "16px",
    color: "var(--muted-faint)",
    flexShrink: 0,
  },
  explanationBox: {
    background: "var(--panel-soft)",
    border: "1px solid var(--border)",
    borderRadius: "10px",
    padding: "16px",
    marginBottom: "20px",
  },
  explanationHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "10px",
  },
  pill: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.1em",
    color: "var(--muted)",
  },
  explanationText: {
    fontFamily: "'Inter', sans-serif",
    fontSize: "14px",
    lineHeight: "1.65",
    color: "var(--text-soft)",
    margin: 0,
  },
  scoreSection: {
    marginBottom: "20px",
    padding: "16px",
    background: "var(--panel-soft)",
    borderRadius: "10px",
  },
  bestMatchRow: {
    marginBottom: "16px",
    padding: "14px",
    background: "rgba(0,229,160,0.04)",
    border: "1px solid rgba(0,229,160,0.12)",
    borderRadius: "10px",
  },
  matchField: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  matchLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "10px",
    color: "var(--muted-soft)",
  },
  matchVal: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: "12px",
    color: "var(--text)",
    fontWeight: 500,
    overflowWrap: "anywhere",
  },
  warningBox: {
    padding: "12px",
    background: "rgba(245,166,35,0.06)",
    border: "1px solid rgba(245,166,35,0.2)",
    borderRadius: "8px",
  },
};
