// src/lib/demoData.js
// Pre-built demo dataset for Treasurer.ai
// Used when backend is unavailable or Demo Mode is active

export const DEMO_CASES = [
  {
    job_id: "demo_001",
    label: "Case 1 — Clean Match",
    status: "matched",
    confidence: 0.91,
    invoice: {
      invoice_number: "INV-2026-0412",
      payer: "Acme Exports Sdn Bhd",
      payee: "GlobalTech Solutions LLC",
      amount: 100.0,
      currency: "USD",
      date: "2026-04-12",
      due_date: "2026-04-19",
      extraction_confidence: 0.97,
      warnings: [],
    },
    payment: {
      sender: "Acme Exports Sdn Bhd",
      receiver: "GlobalTech Solutions LLC",
      amount_sent: 100.0,
      currency_sent: "USD",
      date: "2026-04-13",
      reference: "INV-2026-0412",
      method: "International Wire Transfer",
      extraction_confidence: 0.94,
      warnings: [],
    },
    fx_trace: {
      base_currency: "USD",
      target_currency: "MYR",
      rate: 4.215,
      rate_date: "2026-04-13",
      source: "Frankfurter API",
      converted_amount: 421.5,
    },
    fee_trace: {
      rule_name: "Incoming International Wire",
      percentage_fee: 0.015,
      flat_fee: 0.0,
      fee_amount: 6.32,
      net_after_fee: 415.18,
      currency: "MYR",
    },
    best_match: {
      row_id: "row_003",
      date: "2026-04-13",
      description: "TELEGRAPHIC TRANSFER INV-2026-0412 ACME EXPORTS",
      credit_amount: 415.2,
      debit_amount: null,
      currency: "MYR",
    },
    score_breakdown: {
      date_score: 0.8,
      reference_score: 0.97,
      amount_score: 0.99,
      final_confidence: 0.91,
    },
    explanation:
      "Invoice INV-2026-0412 for USD 100.00 has been successfully reconciled: the bank credited MYR 415.20 on 13 Apr 2026, matching the expected MYR 415.18 after applying the 1.5% incoming wire fee to the USD/MYR rate of 4.215.",
    action_pack: null,
    warnings: [],
    bank_rows: [
      {
        row_id: "row_001",
        date: "2026-04-10",
        description: "SALARY CREDIT APR 2026",
        credit_amount: 5500.0,
        currency: "MYR",
      },
      {
        row_id: "row_002",
        date: "2026-04-11",
        description: "ONLINE TRANSFER UTILITIES",
        credit_amount: 320.0,
        currency: "MYR",
      },
      {
        row_id: "row_003",
        date: "2026-04-13",
        description: "TELEGRAPHIC TRANSFER INV-2026-0412 ACME EXPORTS",
        credit_amount: 415.2,
        currency: "MYR",
        match_score: 0.91,
        is_best: true,
      },
      {
        row_id: "row_004",
        date: "2026-04-15",
        description: "CASH DEPOSIT",
        credit_amount: 200.0,
        currency: "MYR",
        match_score: 0.12,
        is_best: false,
      },
    ],
  },
  {
    job_id: "demo_002",
    label: "Case 2 — Needs Review",
    status: "needs_review",
    confidence: 0.61,
    invoice: {
      invoice_number: "INV-2026-0388",
      payer: "Sunrise Trading Co",
      payee: "GlobalTech Solutions LLC",
      amount: 250.0,
      currency: "USD",
      date: "2026-04-05",
      due_date: "2026-04-12",
      extraction_confidence: 0.91,
      warnings: ["Due date field partially obscured in source image"],
    },
    payment: {
      sender: "Sunrise Trading Co",
      receiver: "GlobalTech Solutions LLC",
      amount_sent: 250.0,
      currency_sent: "USD",
      date: "2026-04-08",
      reference: "INV-2026-0388",
      method: "SWIFT Transfer",
      extraction_confidence: 0.88,
      warnings: [],
    },
    fx_trace: {
      base_currency: "USD",
      target_currency: "MYR",
      rate: 4.21,
      rate_date: "2026-04-08",
      source: "Frankfurter API",
      converted_amount: 1052.5,
    },
    fee_trace: {
      rule_name: "Incoming International Wire",
      percentage_fee: 0.015,
      flat_fee: 0.0,
      fee_amount: 15.79,
      net_after_fee: 1036.71,
      currency: "MYR",
    },
    best_match: {
      row_id: "row_007",
      date: "2026-04-09",
      description: "TT CREDIT SUNRISE TRADING INV388",
      credit_amount: 998.4,
      debit_amount: null,
      currency: "MYR",
    },
    score_breakdown: {
      date_score: 0.8,
      reference_score: 0.72,
      amount_score: 0.33,
      final_confidence: 0.61,
    },
    explanation:
      "The bank credited MYR 998.40, but MYR 1,036.71 was expected after applying the 1.5% wire fee — a shortfall of MYR 38.31 that likely reflects an additional intermediary bank charge deducted in transit; this transaction requires human review before posting.",
    warnings: [
      "Amount received is MYR 38.31 below expected net after fee",
      "Possible intermediary bank deduction detected",
    ],
    action_pack: {
      category: "amount_variance_after_fx_and_fees",
      likely_reason:
        "INV-2026-0388 has a plausible reference/date match, but the closest bank credit differs from the deterministic expected credit. A possible extra bank charge, intermediary deduction, or fee-policy variance should be verified.",
      recommended_next_action:
        "Ask finance to obtain the bank advice or remittance fee breakdown before posting the receipt.",
      missing_evidence_checklist: [
        "Original payment proof with sender, date, amount, currency, and reference visible.",
        "Bank advice or SWIFT/remittance details showing deducted charges.",
        "Confirmation of the receiving bank fee rule used for this account.",
        "Finance approval note before ledger posting.",
      ],
      mock_notification_message:
        "Subject: Finance review required for INV-2026-0388\n\nINV-2026-0388 is marked Needs Review. Expected local credit is MYR 1036.71 after USD/MYR 4.2100 on 2026-04-08 and incoming wire fees. Closest bank row row_007 credited MYR 998.40 on 2026-04-09. Recommended action: ask finance to obtain the bank advice or remittance fee breakdown before posting the receipt.",
      audit_safe_explanation:
        "This action pack uses only extracted invoice/payment fields, the FX trace, fee trace, closest bank row, and deterministic match scores. It does not assume unobserved bank charges or fabricate missing credits.",
      evidence_basis: [
        "fx_rate=4.2100",
        "expected_credit=MYR 1036.71",
        "best_match_row_id=row_007",
        "confidence=0.6100",
      ],
    },
    bank_rows: [
      {
        row_id: "row_005",
        date: "2026-04-06",
        description: "ONLINE TRANSFER REF:SRT-001",
        credit_amount: 450.0,
        currency: "MYR",
        match_score: 0.18,
        is_best: false,
      },
      {
        row_id: "row_006",
        date: "2026-04-08",
        description: "CREDIT CARD REFUND",
        credit_amount: 89.5,
        currency: "MYR",
        match_score: 0.05,
        is_best: false,
      },
      {
        row_id: "row_007",
        date: "2026-04-09",
        description: "TT CREDIT SUNRISE TRADING INV388",
        credit_amount: 998.4,
        currency: "MYR",
        match_score: 0.61,
        is_best: true,
      },
      {
        row_id: "row_008",
        date: "2026-04-10",
        description: "INTERBANK TRANSFER",
        credit_amount: 1050.0,
        currency: "MYR",
        match_score: 0.44,
        is_best: false,
      },
    ],
  },
  {
    job_id: "demo_unmatched_001",
    label: "Case 3 — Unmatched",
    status: "unmatched",
    confidence: 0.12,
    invoice: {
      invoice_number: "INV-2026-0412",
      payer: "Pacific Retail Group",
      payee: "GlobalTech Solutions LLC",
      amount: 100.0,
      currency: "USD",
      date: "2026-05-20",
      due_date: "2026-05-27",
      extraction_confidence: 0.97,
      warnings: [],
    },
    payment: {
      sender: "Pacific Retail Group",
      receiver: "GlobalTech Solutions LLC",
      amount_sent: 100.0,
      currency_sent: "USD",
      date: "2026-05-20",
      reference: "INV-2026-0412",
      method: "International Wire Transfer",
      extraction_confidence: 0.94,
      warnings: [],
    },
    fx_trace: {
      base_currency: "USD",
      target_currency: "MYR",
      rate: 4.33,
      rate_date: "2026-05-20",
      source: "local_fallback_fx_rates",
      converted_amount: 433.0,
    },
    fee_trace: {
      rule_name: "incoming_wire",
      currency: "MYR",
      gross_amount: 433.0,
      percentage_rate: 0.015,
      percentage_fee: 6.5,
      flat_fee: 5.0,
      total_fee: 11.5,
      expected_credit: 421.5,
    },
    best_match: {
      row_id: "row_unmatched_001",
      date: "2026-05-27",
      description: "Incoming transfer unrelated settlement",
      credit_amount: 376.25,
      debit_amount: null,
      currency: "MYR",
    },
    score_breakdown: {
      date_score: 0.0,
      reference_score: 0.41,
      amount_score: 0.0,
      final_confidence: 0.12,
    },
    explanation:
      "INV-2026-0412 could not be matched to a bank credit with sufficient date, reference, and amount agreement.",
    action_pack: {
      category: "no_credible_bank_match",
      likely_reason:
        "The closest bank row is weak on both reference and amount agreement, so it is not credible enough for automated reconciliation.",
      recommended_next_action:
        "Hold the invoice open and request an updated bank statement or proof that the transfer has settled.",
      missing_evidence_checklist: [
        "Original payment proof with sender, date, amount, currency, and reference visible.",
        "Updated bank statement covering the expected settlement window.",
        "Finance approval note before ledger posting.",
      ],
      mock_notification_message:
        "Subject: Finance review required for INV-2026-0412\n\nINV-2026-0412 is marked Unmatched. Expected local credit is MYR 421.50 after USD/MYR 4.3300 on 2026-05-20 and incoming_wire fees. Closest bank row row_unmatched_001 credited MYR 376.25 on 2026-05-27, below the minimum match threshold.",
      audit_safe_explanation:
        "This action pack uses only extracted invoice/payment fields, the FX trace, fee trace, closest bank row, and deterministic match scores. It does not assume unobserved bank charges or fabricate missing credits.",
      evidence_basis: [
        "fx_rate=4.3300",
        "expected_credit=MYR 421.50",
        "best_match_row_id=row_unmatched_001",
        "confidence=0.1200",
      ],
    },
    warnings: [],
    bank_rows: [
      {
        row_id: "row_unmatched_001",
        date: "2026-05-27",
        description: "Incoming transfer unrelated settlement",
        credit_amount: 376.25,
        currency: "MYR",
        match_score: 0.12,
        is_best: true,
      },
    ],
  },
];

export const AGENT_TIMELINE_STEPS = [
  { id: "upload", label: "Documents uploaded", detail: "Invoice PDF, payment proof, bank CSV" },
  { id: "extract", label: "Morpheus extraction complete", detail: "Structured fields parsed from documents" },
  { id: "normalize", label: "Normalization applied", detail: "Dates → YYYY-MM-DD, currencies → ISO codes" },
  { id: "fx", label: "FX rate fetched", detail: "Dated exchange rate from Frankfurter API" },
  { id: "fee", label: "Fee rule applied", detail: "Incoming wire 1.5% deducted" },
  { id: "match", label: "Best match found", detail: "Scoring: date + reference + amount proximity" },
  { id: "explain", label: "Chutes explanation generated", detail: "Discrepancy summary written in business language" },
  { id: "report", label: "PDF report generated", detail: "Audit trail ready for download" },
];
